hello-world-task:
  script:
    - echo Hello World!
    - whoami
    - java --version
    - docker --version
    - /opt/gradle/gradle-8.2/bin/gradle --version
  tags:
    - hackathon-test
  only:
    - back-add-pipline

build-task:
  script:
    - cd back
    - /opt/gradle/gradle-8.2/bin/gradle bootJar
  artifacts:
    paths:
      - back/build/libs/*.jar
  needs:
    - job: hello-world-task
      artifacts: true
  tags:
    - hackathon-test
  only:
    - back-add-pipline
    
create-docker-task:
  script:
    - docker build -t template-image:latest ./back
  needs:
    - job: build-task
  tags:
    - hackathon-test
  only:
    - back-add-pipline
    
run-task:
  script:
    - docker run -d --name template-container --network template-net -p 8080:8080 template-image:latest
  needs:
    - job: create-docker-task
  tags:
    - hackathon-test
  only:
    - back-add-pipline    
