hello-world-task:
  script:
    - echo Hello World!
    - whoami
    - java --version
    - docker --version
    - /opt/gradle/gradle-8.2/bin/gradle --version
  tags:
    - hackathon-test
  only:
    - back-add-pipline

build-task:
  script:
    - cd back
    - /opt/gradle/gradle-8.2/bin/gradle bootJar
  artifacts:
    paths:
      - back/build/libs/*.jar
  needs:
    - job: hello-world-task
      artifacts: true
  tags:
    - hackathon-test
  only:
    - back-add-pipline